# Generated by Django 3.2 on 2021-04-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dose',
            old_name='clinic_name',
            new_name='clinic',
        ),
        migrations.RenameField(
            model_name='dose',
            old_name='product_name',
            new_name='product',
        ),
    ]
